
all:
	echo nothing to do.

convertA:
	bash convert_accesslog.sh apache2

importA:
	bash import_accesslog.sh apache2


convertB:
	bash convert_accesslog.sh oldtype

importB:
	bash import_accesslog.sh oldtype




