
all:
	echo nothing to do.

convert1:
	bash convert_accesslog.sh sumibiorg

import1:
	bash import_accesslog.sh  sumibiorg


convert2:
	bash convert_accesslog.sh oldtype

import2:
	bash import_accesslog.sh oldtype




